/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-25 22:45:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title>SaberForge - About us</title>\r\n");
      out.write("\t\t<link href=\"ressources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"ressources/css/style.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"ressources/css/ui-lightness/jquery-ui-1.9.2.custom.css\">\r\n");
      out.write("\r\n");
      out.write("\t    <script src=\"ressources/js/jquery-1.10.2.js\"></script>\r\n");
      out.write("    \t<script src=\"ressources/js/jquery-ui-1.9.2.custom.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t<p class=\"aboutusText\">\r\n");
      out.write("\t\t\t\tSaberForge Industries is one of the largest weapon manufacturers of the galaxy \r\n");
      out.write("\t\t\t\talongside Merr-Sonn Munitions, Inc and SoroSuub. SaberForge is the leader of the market for\r\n");
      out.write("\t\t\t\tpersonal weapons and light artillery. Our corporation is most famous for the good quality of\r\n");
      out.write("\t\t\t\tour blasters although its product range also includes onboard weapons on spaceships such as turbolasers, \r\n");
      out.write("\t\t\t\tion cannon and missiles.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div class=\"aboutusIllu\">\r\n");
      out.write("\t\t\t\t<span class=\"illu1-1\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"illu1-2\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p class=\"aboutusText\">\r\n");
      out.write("\t\t\t\tSaberForge decided recently to make the lightsaber selling its main activity. We provide high quality and \r\n");
      out.write("\t\t\t\treliable dueling weapons of all kinds.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div class=\"aboutusIllu\">\r\n");
      out.write("\t\t\t\t<span class=\"illu2-1\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"illu2-2\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
